// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQgIj1nAVDkqb26yLAND8x4_hzNxhL0tc',
    appId: '1:1013171447198:web:dc2628acf647aa36c3228f',
    messagingSenderId: '1013171447198',
    projectId: 'breathe-b8b94',
    authDomain: 'breathe-b8b94.firebaseapp.com',
    storageBucket: 'breathe-b8b94.firebasestorage.app',
    measurementId: 'G-QPYCV43BD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYP_--IbYZT4XG-_kJHT5lnCjh8TT_9QU',
    appId: '1:1013171447198:android:43f3d12161287606c3228f',
    messagingSenderId: '1013171447198',
    projectId: 'breathe-b8b94',
    storageBucket: 'breathe-b8b94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6dQW7AoYYxoKr1DMQI2p6rQ8gqdVoR-w',
    appId: '1:1013171447198:ios:197c1072ff835f5fc3228f',
    messagingSenderId: '1013171447198',
    projectId: 'breathe-b8b94',
    storageBucket: 'breathe-b8b94.firebasestorage.app',
    androidClientId: '1013171447198-q8vmvj0qpoo4hv0a6v86piq5q3nle3cr.apps.googleusercontent.com',
    iosClientId: '1013171447198-2ekdd4e6ldollskspjfefksr516tfolq.apps.googleusercontent.com',
    iosBundleId: 'com.example.breathe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6dQW7AoYYxoKr1DMQI2p6rQ8gqdVoR-w',
    appId: '1:1013171447198:ios:197c1072ff835f5fc3228f',
    messagingSenderId: '1013171447198',
    projectId: 'breathe-b8b94',
    storageBucket: 'breathe-b8b94.firebasestorage.app',
    androidClientId: '1013171447198-q8vmvj0qpoo4hv0a6v86piq5q3nle3cr.apps.googleusercontent.com',
    iosClientId: '1013171447198-2ekdd4e6ldollskspjfefksr516tfolq.apps.googleusercontent.com',
    iosBundleId: 'com.example.breathe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQgIj1nAVDkqb26yLAND8x4_hzNxhL0tc',
    appId: '1:1013171447198:web:e6ddee7a8ee4c9f2c3228f',
    messagingSenderId: '1013171447198',
    projectId: 'breathe-b8b94',
    authDomain: 'breathe-b8b94.firebaseapp.com',
    storageBucket: 'breathe-b8b94.firebasestorage.app',
    measurementId: 'G-NZJ8SSRW4E',
  );

}